//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace flight_management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AEROPORTURI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AEROPORTURI()
        {
            this.ZBORURIs = new HashSet<ZBORURI>();
        }
    
        public decimal ID_AEROPORTURI { get; set; }
        public string NUME_AEROPORT { get; set; }
        public string COD_AEROPORT { get; set; }
        public string ORAS { get; set; }
        public string TARA { get; set; }
        public byte NR_PISTE { get; set; }
        public byte NR_PORTI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZBORURI> ZBORURIs { get; set; }
    }
}
