//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace flight_management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILETE
    {
        public decimal ID_BILETE { get; set; }
        public decimal ID_PASAGERI { get; set; }
        public decimal ID_ZBORURI { get; set; }
        public System.DateTime DATA_REZERVARE { get; set; }
        public bool CLASA { get; set; }
        public byte LOC { get; set; }
        public decimal PRET { get; set; }
    
        public virtual PASAGERI PASAGERI { get; set; }
        public virtual ZBORURI ZBORURI { get; set; }
    }
}
