//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace flight_management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANII_AERIENE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMPANII_AERIENE()
        {
            this.ZBORURIs = new HashSet<ZBORURI>();
        }
    
        public decimal ID_COMPANII { get; set; }
        public string NUME_COMPANIE { get; set; }
        public string COD_COMPANIE { get; set; }
        public string TARA { get; set; }
        public short AN_INFIINTARE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZBORURI> ZBORURIs { get; set; }
    }
}
