//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace flight_management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PASAGERI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PASAGERI()
        {
            this.BILETEs = new HashSet<BILETE>();
        }
    
        public decimal ID_PASAGERI { get; set; }
        public string NUME_PASAGER { get; set; }
        public string PRENUME_PASAGER { get; set; }
        public System.DateTime DATA_NASTERII { get; set; }
        public string NATIONALITATE { get; set; }
        public string NR_PASAPORT { get; set; }
        public string GEN { get; set; }
        public string NR_TEL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILETE> BILETEs { get; set; }
    }
}
