//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace flight_management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZBORURI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ZBORURI()
        {
            this.BILETEs = new HashSet<BILETE>();
        }
    
        public decimal ID_ZBORURI { get; set; }
        public decimal ID_COMPANII { get; set; }
        public string AEROPORT_PLECARE { get; set; }
        public string AEROPORT_SOSIRE { get; set; }
        public System.DateTime ORA_PLECARE { get; set; }
        public System.DateTime ORA_SOSIRE { get; set; }
        public short DURATA_ZBOR { get; set; }
        public string TIP_AVION { get; set; }
        public decimal ID_AEROPORTURI { get; set; }
    
        public virtual AEROPORTURI AEROPORTURI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILETE> BILETEs { get; set; }
        public virtual COMPANII_AERIENE COMPANII_AERIENE { get; set; }
    }
}
